name: Build and deploy ASP.Net Core app to Azure Web App - RaymarEquipApp01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build RaymarEquipmentInventory.csproj --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish RaymarEquipmentInventory.csproj -c Release -o "./myapp"
          Compress-Archive -Path "./myapp/*" -DestinationPath "./myapp.zip"
        shell: pwsh

      - name: Confirm Package File Exists (Debug)
        run: |
          if [ -f "./myapp.zip" ]; then echo "Package found"; else echo "Package not found"; exit 1; fi
        shell: bash
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE2D3F8CD53D461983D7F2E649F6909C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C25373A2BA41446BB3EC203AE590F8AF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_021B4E57428C45B3B20D8702858BB73D }}
          
      - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT to true
        run: az webapp config appsettings set --name 'RaymarEquipApp01' --resource-group 'RaymarEquipService' --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
        shell: pwsh

      # Restart Web App to clear any locked files
      - name: Restart Azure Web App
        run: |
          az webapp restart --name 'RaymarEquipApp01' --resource-group 'RaymarEquipService'
        shell: pwsh

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RaymarEquipApp01'
          slot-name: 'Production'
          package: './myapp.zip'
          clean: true

