name: Build and deploy ASP.Net Core app to Azure Web App - RaymarEquipApp01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build RaymarEquipmentInventory.csproj --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish RaymarEquipmentInventory.csproj -c Release -o "./myapp"
          Compress-Archive -Path "./myapp/*" -DestinationPath "./myapp.zip"
        shell: pwsh

      - name: Confirm Package File Exists (Debug)
        run: |
          if [ -f "./myapp.zip" ]; then echo "Package found"; else echo "Package not found"; exit 1; fi
        shell: bash
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
     # Stop the Web App to release any file locks
      - name: Stop Azure Web App
        run: |
          az webapp stop --name 'RaymarEquipApp01' --resource-group 'RaymarEquipService'
        shell: pwsh

      # Set WEBSITE_RUN_FROM_PACKAGE to enable read-only deployment
      - name: Set WEBSITE_RUN_FROM_PACKAGE to 0
        run: az webapp config appsettings set --name 'RaymarEquipApp01' --resource-group 'RaymarEquipService' --settings WEBSITE_RUN_FROM_PACKAGE=0
        shell: pwsh

      # Deploy to Azure Web App with clean option
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RaymarEquipApp01'
          slot-name: 'Production'
          package: './myapp.zip'
          clean: true

      # Start the Web App after deployment
      - name: Start Azure Web App
        run: |
          az webapp start --name 'RaymarEquipApp01' --resource-group 'RaymarEquipService'
        shell: pwsh


