name: Build and deploy ASP.Net Core app to Azure Web App - RaymarInventoryAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish RaymarEquipmentInventory.csproj -c Release -o ./output

      - name: List contents of output directory
        run: ls -R ./output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'  # Change to 'Development' if targeting a dev slot
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: List contents of downloaded directory
        run: ls -R 

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RaymarInventoryAPI'
          slot-name: 'Development'  # Adjust this based on environment
          package: './output'







          
