# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - RaymarInventoryAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build RaymarEquipmentInventory.csproj --configuration Release
        env:                         # Add environment variable for the build step now.
          SAMSARA_API_TOKEN: ${{ secrets.SAMSARA_API_TOKEN }}

      - name: dotnet publish
        run: dotnet publish RaymarEquipmentInventory.csproj -c Release -o ./myapp
        env:  # Add environment variable for the publish step
          SAMSARA_API_TOKEN: ${{ secrets.SAMSARA_API_TOKEN }}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BDA90BD87DAA4F7298817A3E378FABCF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_10FE8A6958094F91871D24A1597FF604 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_937BB13F0B5F49359EE609598FE91C44 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RaymarInventoryAPI'
          slot-name: 'Production'
          package: .
        env:                         # Add environment variable for the deploy step
            SAMSARA_API_TOKEN: ${{ secrets.SAMSARA_API_TOKEN }}
