// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class BillingInformation
{
    public int BillingId { get; set; }

    public string Pono { get; set; }

    public int? Kilometers { get; set; }

    public int SheetId { get; set; }

    public int? BillingPersonId { get; set; }

    public int? CustomerId { get; set; }

    public string Notes { get; set; }

    public string UnitNo { get; set; }

    public string WorkLocation { get; set; }

    public string JobSiteCity { get; set; }

    public string WorkDescription { get; set; }

    public string CustPath { get; set; }

    public virtual Person BillingPerson { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<ServiceDescription> ServiceDescriptions { get; set; } = new List<ServiceDescription>();

    public virtual WorkOrderSheet Sheet { get; set; }
}