// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class ChargeItemRateHistory
{
    public int RateHistoryId { get; set; }

    public int ItemId { get; set; }

    public decimal Rate { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public string SourceTag { get; set; }

    public virtual ChargeItem Item { get; set; }
}