// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class ChargeItem
{
    public int ItemId { get; set; }

    public string QbFullName { get; set; }

    public string DisplayName { get; set; }

    public string Category { get; set; }

    public string UoM { get; set; }

    public string PricingModel { get; set; }

    public decimal DefaultRate { get; set; }

    public string TaxCode { get; set; }

    public string ClassName { get; set; }

    public bool? IsActive { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<ChargeItemRateHistory> ChargeItemRateHistories { get; set; } = new List<ChargeItemRateHistory>();

    public virtual ICollection<WorkOrderFee> WorkOrderFees { get; set; } = new List<WorkOrderFee>();

    public virtual ICollection<WorkOrderLine> WorkOrderLines { get; set; } = new List<WorkOrderLine>();
}