// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class CustomerHierarchyWork
{
    public int StartCustomerId { get; set; }

    public DateTime RequestedAt { get; set; }

    public string Reason { get; set; }
}