// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class CustomerTombstone
{
    public int CustomerId { get; set; }

    public DateTime DeletedAt { get; set; }
}