// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Id { get; set; }

    public string ParentId { get; set; }

    public string CustomerName { get; set; }

    public string ParentName { get; set; }

    public string Company { get; set; }

    public string FullName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string AccountNumber { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Notes { get; set; }

    public string JobStatus { get; set; }

    public DateTime? JobStartDate { get; set; }

    public DateTime? JobProjectedEndDate { get; set; }

    public string JobDescription { get; set; }

    public string JobType { get; set; }

    public string JobTypeId { get; set; }

    public string Description { get; set; }

    public int SubLevelId { get; set; }

    public string FullAddress { get; set; }

    public DateTime LastUpdated { get; set; }

    public string UpdateType { get; set; }

    public string MaterializedPath { get; set; }

    public string PathIds { get; set; }

    public int? Depth { get; set; }

    public int? RootId { get; set; }

    public DateTime? QbLastUpdated { get; set; }

    public bool? IsActive { get; set; }

    public DateTime ServerUpdatedAt { get; set; }

    public byte[] ChangeVersion { get; set; }

    public bool? EffectiveActive { get; set; }

    public int? ParentCustomerId { get; set; }

    public virtual ICollection<BillingInformation> BillingInformations { get; set; } = new List<BillingInformation>();

    public virtual ICollection<Customer> InverseParent { get; set; } = new List<Customer>();

    public virtual ICollection<Customer> InverseParentCustomer { get; set; } = new List<Customer>();

    public virtual Customer Parent { get; set; }

    public virtual Customer ParentCustomer { get; set; }
}