// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RaymarEquipmentInventory.Models
{
    public partial class Customers_ChangesSinceVersionResult
    {
        public int CustomerID { get; set; }
        public string ID { get; set; }
        public string ParentID { get; set; }
        public string CustomerName { get; set; }
        public string FullAddress { get; set; }
        public string MaterializedPath { get; set; }
        public string PathIds { get; set; }
        public int? Depth { get; set; }
        public int? RootId { get; set; }
        public bool IsActive { get; set; }
        public DateTime? QbLastUpdated { get; set; }
        public DateTime ServerUpdatedAt { get; set; }
        public byte[] ChangeVersion { get; set; }
    }
}
