// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class DiAllowedKeyword
{
    public int AllowedKeywordId { get; set; }

    public int CategoryId { get; set; }

    public string Keyword { get; set; }

    public string Notes { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual DiCategory Category { get; set; }
}