// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class DiCandidateKeyword
{
    public int CandidateKeywordId { get; set; }

    public int CategoryId { get; set; }

    public string Keyword { get; set; }

    public int? SourcePlaceId { get; set; }

    public DateTime FirstSeenAtUtc { get; set; }

    public DateTime LastSeenAtUtc { get; set; }

    public int SeenCount { get; set; }

    public decimal Confidence { get; set; }

    public byte Status { get; set; }

    public string Notes { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual DiCategory Category { get; set; }

    public virtual DiPlace SourcePlace { get; set; }
}