// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class DiCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual ICollection<DiAllowedKeyword> DiAllowedKeywords { get; set; } = new List<DiAllowedKeyword>();

    public virtual ICollection<DiCandidateKeyword> DiCandidateKeywords { get; set; } = new List<DiCandidateKeyword>();

    public virtual ICollection<DiItemKeyword> DiItemKeywords { get; set; } = new List<DiItemKeyword>();

    public virtual ICollection<DiPlace> DiPlaces { get; set; } = new List<DiPlace>();
}