// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class DiPlaceAlias
{
    public int PlaceAliasId { get; set; }

    public int PlaceId { get; set; }

    public string Alias { get; set; }

    public string Notes { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual DiPlace Place { get; set; }
}