// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Document
{
    public int DocumentId { get; set; }

    public int SheetId { get; set; }

    public int DocumentTypeId { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public DateTime UploadDate { get; set; }

    public string UploadedBy { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual WorkOrderSheet Sheet { get; set; }
}