// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class DriveFileMetadataBackup20250910
{
    public int MetadataId { get; set; }

    public string DriveFileId { get; set; }

    public string Name { get; set; }

    public string MimeType { get; set; }

    public string FolderId { get; set; }

    public string Description { get; set; }

    public DateTimeOffset? ModifiedTime { get; set; }

    public long? SizeBytes { get; set; }

    public string Md5Checksum { get; set; }

    public string WebViewLink { get; set; }

    public string WebContentLink { get; set; }

    public string LastModUser { get; set; }

    public bool IsTemplateFile { get; set; }

    public bool IsTrashed { get; set; }

    public DateTimeOffset LastSeenAt { get; set; }

    public int? PdfTagId { get; set; }

    public string CategoriesCsv { get; set; }

    public string Notes { get; set; }

    public string CleanDescription { get; set; }

    public string FileNameLower { get; set; }
}