// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class EmailNotificationType
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual ICollection<EmailNotificationRecipient> EmailNotificationRecipients { get; set; } = new List<EmailNotificationRecipient>();
}