// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class EmailNotificationRecipient
{
    public int Id { get; set; }

    public int NotificationTypeId { get; set; }

    public string EmailAddress { get; set; }

    public string DisplayName { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual EmailNotificationType NotificationType { get; set; }
}