// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class ExpensesQb
{
    public int ExpensesQbid { get; set; }

    public string EntityType { get; set; }

    public int EntityId { get; set; }

    public string ListId { get; set; }
}