// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class FailedSyncLog
{
    public int FailedSyncLogId { get; set; }

    public int SheetId { get; set; }

    public string Reason { get; set; }

    public DateTime Timestamp { get; set; }
}