// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class FeeVisibility
{
    public int LabourTypeId { get; set; }

    public int TechnicianWorkOrderId { get; set; }

    public bool IsVisible { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual LabourType LabourType { get; set; }
}