// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class FlatLabour
{
    public int FlatLabourId { get; set; }

    public string LabourName { get; set; }

    public string LabourDescription { get; set; }

    public string FeeAndExpense { get; set; }

    public int? LabourTypeId { get; set; }

    public decimal Price { get; set; }

    public virtual LabourType LabourType { get; set; }

    public virtual ICollection<TechnicianAndType> TechnicianAndTypes { get; set; } = new List<TechnicianAndType>();

    public virtual ICollection<WorkOrderFee> WorkOrderFees { get; set; } = new List<WorkOrderFee>();
}