// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class GoogleDriveFolder
{
    public int Id { get; set; }

    public string FolderName { get; set; }

    public string ParentFolderId { get; set; }

    public string FolderId { get; set; }

    public DateTime? CreatedAt { get; set; }
}