// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class HourlyLabourType
{
    public int LabourTypeId { get; set; }

    public string LabourTypeDescription { get; set; }

    public bool IsDefault { get; set; }
}