// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class InventoryStaging
{
    public long Id { get; set; }

    public Guid RunId { get; set; }

    public string ListId { get; set; }

    public string FullName { get; set; }

    public string EditSequence { get; set; }

    public decimal QuantityOnHand { get; set; }

    public decimal? SalesPrice { get; set; }

    public decimal? PurchaseCost { get; set; }

    public DateTime CreatedAtUtc { get; set; }
}