// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class InventoryDataArchive
{
    public int InventoryId { get; set; }

    public string ItemName { get; set; }

    public string ManufacturerPartNumber { get; set; }

    public string Description { get; set; }

    public decimal? Cost { get; set; }

    public decimal? SalesPrice { get; set; }

    public int? ReorderPoint { get; set; }

    public int? OnHand { get; set; }

    public decimal? AverageCost { get; set; }

    public int? IncomeAccountId { get; set; }

    public string QuickBooksInvId { get; set; }

    public DateTime? LastRestockedDate { get; set; }
}