// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class InvoiceLine
{
    public int InvoiceLineId { get; set; }

    public int InvoiceId { get; set; }

    public int LineNumber { get; set; }

    public string ItemListId { get; set; }

    public string ItemNameSnapshot { get; set; }

    public string Description { get; set; }

    public decimal Qty { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Amount { get; set; }

    public string ClassRef { get; set; }

    public DateTime? ServiceDate { get; set; }

    public string TaxCodeRef { get; set; }

    public string SourceType { get; set; }

    public string SourceId { get; set; }

    public string Uom { get; set; }

    public bool? IsTaxable { get; set; }

    public virtual Invoice Invoice { get; set; }
}