// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public int WorkOrderId { get; set; }

    public int? CustomerId { get; set; }

    public string CustomerListId { get; set; }

    public string RefNumber { get; set; }

    public DateTime TxnDate { get; set; }

    public DateTime? DueDate { get; set; }

    public string TermsRef { get; set; }

    public string Ponumber { get; set; }

    public string Memo { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? Total { get; set; }

    public string Currency { get; set; }

    public string Status { get; set; }

    public string ErrorMessage { get; set; }

    public byte[] SourceHash { get; set; }

    public string QbTxnId { get; set; }

    public string QbEditSequence { get; set; }

    public int ExportAttemptCount { get; set; }

    public DateTime? LastExportAttemptAt { get; set; }

    public DateTime? ExportedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] ChangeVersion { get; set; }

    public virtual ICollection<InvoiceLine> InvoiceLines { get; set; } = new List<InvoiceLine>();
}