// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RaymarEquipmentInventory.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RaymarEquipmentInventory.Models
{
    public partial interface IRaymarInventoryDBContextProcedures
    {
        Task<int> Qbwc_EndSessionAsync(Guid? RunId, string LastError, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Qbwc_LogMessageAsync(Guid? RunId, string Method, string Direction, int? StatusCode, string HResult, string Message, string CompanyFile, string PayloadXml, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Qbwc_StartSessionAsync(Guid? RunId, string QbwcUser, string CompanyFile, string Ticket, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_DI_PromoteCandidateKeywordsResult>> usp_DI_PromoteCandidateKeywordsAsync(int? MinSeenCount, decimal? MinConfidence, bool? RequireApproval, bool? DryRun, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
