// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Labour
{
    public int LabourId { get; set; }

    public DateTime DateOfLabour { get; set; }

    public DateTime? StartLabour { get; set; }

    public DateTime? FinishLabour { get; set; }

    public int? OttotalHrs { get; set; }

    public int? OttotalMin { get; set; }

    public bool FlatRateJob { get; set; }

    public string FlatRateJobDescription { get; set; }

    public int? TechnicianWorkOrderId { get; set; }

    public string WorkDescription { get; set; }

    public virtual TechnicianWorkOrder TechnicianWorkOrder { get; set; }
}