// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class LabourType
{
    public int LabourTypeId { get; set; }

    public string LabourTypeDescription { get; set; }

    public virtual ICollection<FlatLabour> FlatLabours { get; set; } = new List<FlatLabour>();

    public virtual ICollection<WorkOrderFee> WorkOrderFees { get; set; } = new List<WorkOrderFee>();
}