// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class MileageAndTime
{
    public int MilageTimeId { get; set; }

    public int SheetId { get; set; }

    public DateTime DateOfMileageTime { get; set; }

    public DateTime StartTravel { get; set; }

    public DateTime FinishTravel { get; set; }

    public int? StartOdometerKm { get; set; }

    public int? FinishOdometerKm { get; set; }

    public int? TimeTotalHrs { get; set; }

    public int? TimeTotalMin { get; set; }

    public int? SegmentNumber { get; set; }

    public int? TotalDistance { get; set; }

    public int? TotalOthours { get; set; }

    public int? TotalOtminutes { get; set; }

    public bool IsOvertime { get; set; }

    public virtual WorkOrderSheet Sheet { get; set; }
}