// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class NextWorkOrderNumber
{
    public int Id { get; set; }

    public int Wonumber { get; set; }
}