// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models
{
    public partial class PartsUsed
    {
        public int PartUsedId { get; set; }

        public int QtyUsed { get; set; }

        // Mark QuickBooksInvId as nullable and initialize it with a non-null value
        public string? QuickBooksInvId { get; set; } = string.Empty;

        // Mark Notes as nullable and initialize it with a non-null value
        public string? Notes { get; set; } = string.Empty;

        // Optionally make SheetId nullable if it's not required
        public int? SheetId { get; set; }

        public virtual InventoryDatum? QuickBooksInv { get; set; }

        public virtual WorkOrderSheet? Sheet { get; set; }
    }
}