// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Pdfdocument
{
    public int PdfdocumentId { get; set; }

    public int SheetId { get; set; }

    public string FileName { get; set; }

    public string Description { get; set; }

    public string UploadedBy { get; set; }

    public DateTime UploadDate { get; set; }

    public string FileUrl { get; set; }

    public string DriveFileId { get; set; }

    public string WorkOrderFolderId { get; set; }

    public string PdffolderId { get; set; }

    public string AzureBlobPath { get; set; }

    public virtual WorkOrderSheet Sheet { get; set; }
}