// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Pdftag
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public string Categories { get; set; }

    public int? LabourTypeId { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<DriveFileMetadatum> DriveFileMetadata { get; set; } = new List<DriveFileMetadatum>();

    public virtual LabourType LabourType { get; set; }
}