// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class PdfviewedForSheet
{
    public int SheetId { get; set; }

    public string FileName { get; set; }

    public DateTime ViewedAt { get; set; }
}