// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class Person
{
    public int PersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string RoleName { get; set; }

    public string PhoneOne { get; set; }

    public string Email { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? RoleId { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BillingInformation> BillingInformations { get; set; } = new List<BillingInformation>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Technician> Technicians { get; set; } = new List<Technician>();
}