// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class QbitemCatalog
{
    public int ItemId { get; set; }

    public string ListId { get; set; }

    public string Type { get; set; }

    public string Name { get; set; }

    public string FullName { get; set; }

    public string EditSequence { get; set; }

    public decimal? SalesPrice { get; set; }

    public decimal? PurchaseCost { get; set; }

    public string SalesDesc { get; set; }

    public string PurchaseDesc { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? TimeModified { get; set; }

    public DateTime ServerUpdatedAt { get; set; }

    public DateTime LastUpdated { get; set; }
}