// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class QbwcSession
{
    public long Id { get; set; }

    public Guid RunId { get; set; }

    public DateTime StartedAtUtc { get; set; }

    public DateTime? EndedAtUtc { get; set; }

    public string QbwcUser { get; set; }

    public string CompanyFile { get; set; }

    public string Ticket { get; set; }

    public string ClientVersion { get; set; }

    public string ServerVersion { get; set; }

    public string LastError { get; set; }

    public string Notes { get; set; }
}