// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class QbwcMessage
{
    public long Id { get; set; }

    public Guid RunId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public string Method { get; set; }

    public string Direction { get; set; }

    public int? StatusCode { get; set; }

    public string Hresult { get; set; }

    public string Message { get; set; }

    public string CompanyFile { get; set; }

    public string PayloadXml { get; set; }
}