// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class QbXmlLog
{
    public long LogId { get; set; }

    public Guid RunId { get; set; }

    public Guid RequestGuid { get; set; }

    public string Direction { get; set; }

    public string Phase { get; set; }

    public string RequestType { get; set; }

    public string CompanyFile { get; set; }

    public string IteratorId { get; set; }

    public int? InvoiceId { get; set; }

    public string RefNumber { get; set; }

    public int? StatusCode { get; set; }

    public string Hresult { get; set; }

    public string Message { get; set; }

    public byte[] PayloadSha256 { get; set; }

    public int? PayloadSizeBytes { get; set; }

    public int? DurationMs { get; set; }

    public string PayloadXml { get; set; }

    public DateTime CreatedAtUtc { get; set; }
}