// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RaymarEquipmentInventory.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RaymarEquipmentInventory.Models
{
    public partial class RaymarInventoryDBContext
    {
        private IRaymarInventoryDBContextProcedures _procedures;

        public virtual IRaymarInventoryDBContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RaymarInventoryDBContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRaymarInventoryDBContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usp_DI_PromoteCandidateKeywordsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class RaymarInventoryDBContextProcedures : IRaymarInventoryDBContextProcedures
    {
        private readonly RaymarInventoryDBContext _context;

        public RaymarInventoryDBContextProcedures(RaymarInventoryDBContext context)
        {
            _context = context;
        }

        public virtual async Task<int> Qbwc_EndSessionAsync(Guid? RunId, string LastError, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RunId",
                    Value = RunId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "LastError",
                    Size = -1,
                    Value = LastError ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Qbwc_EndSession] @RunId, @LastError", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Qbwc_LogMessageAsync(Guid? RunId, string Method, string Direction, int? StatusCode, string HResult, string Message, string CompanyFile, string PayloadXml, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RunId",
                    Value = RunId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "Method",
                    Size = 40,
                    Value = Method ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Direction",
                    Size = 10,
                    Value = Direction ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "StatusCode",
                    Value = StatusCode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "HResult",
                    Size = 100,
                    Value = HResult ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Message",
                    Size = 8000,
                    Value = Message ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CompanyFile",
                    Size = 800,
                    Value = CompanyFile ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PayloadXml",
                    Value = PayloadXml ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Xml,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Qbwc_LogMessage] @RunId, @Method, @Direction, @StatusCode, @HResult, @Message, @CompanyFile, @PayloadXml", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> Qbwc_StartSessionAsync(Guid? RunId, string QbwcUser, string CompanyFile, string Ticket, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RunId",
                    Value = RunId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.UniqueIdentifier,
                },
                new SqlParameter
                {
                    ParameterName = "QbwcUser",
                    Size = 200,
                    Value = QbwcUser ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CompanyFile",
                    Size = 800,
                    Value = CompanyFile ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Ticket",
                    Size = 400,
                    Value = Ticket ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[Qbwc_StartSession] @RunId, @QbwcUser, @CompanyFile, @Ticket", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_DI_PromoteCandidateKeywordsResult>> usp_DI_PromoteCandidateKeywordsAsync(int? MinSeenCount, decimal? MinConfidence, bool? RequireApproval, bool? DryRun, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MinSeenCount",
                    Value = MinSeenCount ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MinConfidence",
                    Precision = 5,
                    Scale = 4,
                    Value = MinConfidence ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "RequireApproval",
                    Value = RequireApproval ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "DryRun",
                    Value = DryRun ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_DI_PromoteCandidateKeywordsResult>("EXEC @returnValue = [dbo].[usp_DI_PromoteCandidateKeywords] @MinSeenCount, @MinConfidence, @RequireApproval, @DryRun", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
