// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RaymarEquipmentInventory.Models;

public partial class RaymarInventoryDBContext : DbContext
{
    public RaymarInventoryDBContext(DbContextOptions<RaymarInventoryDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BillingInformation> BillingInformations { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Document> Documents { get; set; }

    public virtual DbSet<DocumentType> DocumentTypes { get; set; }

    public virtual DbSet<IncomeAccount> IncomeAccounts { get; set; }

    public virtual DbSet<InventoryDatum> InventoryData { get; set; }

    public virtual DbSet<InventoryDocument> InventoryDocuments { get; set; }

    public virtual DbSet<Labour> Labours { get; set; }

    public virtual DbSet<MileageAndTime> MileageAndTimes { get; set; }

    public virtual DbSet<PartsUsed> PartsUseds { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<ServiceDescription> ServiceDescriptions { get; set; }

    public virtual DbSet<Technician> Technicians { get; set; }

    public virtual DbSet<TechnicianExperience> TechnicianExperiences { get; set; }

    public virtual DbSet<TechnicianLicence> TechnicianLicences { get; set; }

    public virtual DbSet<TechnicianWorkOrder> TechnicianWorkOrders { get; set; }

    public virtual DbSet<VehicleDatum> VehicleData { get; set; }

    public virtual DbSet<VehicleHistory> VehicleHistories { get; set; }

    public virtual DbSet<VehicleTravelLog> VehicleTravelLogs { get; set; }

    public virtual DbSet<VehicleWorkOrder> VehicleWorkOrders { get; set; }

    public virtual DbSet<WorkOrderCounter> WorkOrderCounters { get; set; }

    public virtual DbSet<WorkOrderSheet> WorkOrderSheets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BillingInformation>(entity =>
        {
            entity.HasKey(e => e.BillingId).HasName("PK__BillingI__F1656D132D42E93A");

            entity.ToTable("BillingInformation");

            entity.Property(e => e.BillingId).HasColumnName("BillingID");
            entity.Property(e => e.BillingPersonId).HasColumnName("BillingPersonID");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.Pono)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("PONo");
            entity.Property(e => e.SheetId).HasColumnName("SheetID");
            entity.Property(e => e.UnitNo)
                .HasMaxLength(35)
                .IsUnicode(false);
            entity.Property(e => e.WorkLocation)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.BillingPerson).WithMany(p => p.BillingInformations)
                .HasForeignKey(d => d.BillingPersonId)
                .HasConstraintName("FK_Billing_Persons");

            entity.HasOne(d => d.Customer).WithMany(p => p.BillingInformations)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_BillingInformation_Customers");

            entity.HasOne(d => d.Sheet).WithMany(p => p.BillingInformations)
                .HasForeignKey(d => d.SheetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BillingInformation_WorkOrderSheet");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId);

            entity.HasIndex(e => e.Id, "UQ_Customers_ID").IsUnique();

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.AccountNumber).HasMaxLength(50);
            entity.Property(e => e.Company).HasMaxLength(255);
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(100);
            entity.Property(e => e.FullAddress).IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.Id)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ID");
            entity.Property(e => e.JobProjectedEndDate).HasColumnType("date");
            entity.Property(e => e.JobStartDate).HasColumnType("date");
            entity.Property(e => e.JobStatus).HasMaxLength(100);
            entity.Property(e => e.JobType).HasMaxLength(100);
            entity.Property(e => e.JobTypeId).HasMaxLength(50);
            entity.Property(e => e.LastName).HasMaxLength(100);
            entity.Property(e => e.ParentId)
                .HasMaxLength(50)
                .HasColumnName("ParentID");
            entity.Property(e => e.ParentName).HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(50);

            entity.HasOne(d => d.Parent).WithMany(p => p.InverseParent)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_ParentCustomer");
        });

        modelBuilder.Entity<Document>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK__Document__1ABEEF6F3CB9DA3E");

            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.DocumentTypeId).HasColumnName("DocumentTypeID");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("FileURL");
            entity.Property(e => e.SheetId).HasColumnName("SheetID");
            entity.Property(e => e.UploadDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UploadedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.DocumentType).WithMany(p => p.Documents)
                .HasForeignKey(d => d.DocumentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documents_DocumentTypes");

            entity.HasOne(d => d.Sheet).WithMany(p => p.Documents)
                .HasForeignKey(d => d.SheetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Documents_WorkOrderSheet");
        });

        modelBuilder.Entity<DocumentType>(entity =>
        {
            entity.HasKey(e => e.DocumentTypeId).HasName("PK__Document__DBA390C1C2B39F2E");

            entity.Property(e => e.DocumentTypeId).HasColumnName("DocumentTypeID");
            entity.Property(e => e.DocumentTypeName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MimeType)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<IncomeAccount>(entity =>
        {
            entity.HasKey(e => e.IncomeAccountId).HasName("PK__IncomeAc__B36A206EFC75E628");

            entity.ToTable("IncomeAccount");

            entity.Property(e => e.IncomeAccountId).HasColumnName("IncomeAccountID");
            entity.Property(e => e.AccountName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('Sales')");
        });

        modelBuilder.Entity<InventoryDatum>(entity =>
        {
            entity.HasKey(e => e.InventoryId).HasName("PK__Inventor__F5FDE6D30BA95700");

            entity.HasIndex(e => e.QuickBooksInvId, "IX_Unique_QuickBooksInvID")
                .IsUnique()
                .HasFilter("([QuickBooksInvID] IS NOT NULL)");

            entity.Property(e => e.InventoryId).HasColumnName("InventoryID");
            entity.Property(e => e.AverageCost).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Cost).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IncomeAccountId).HasColumnName("IncomeAccountID");
            entity.Property(e => e.ItemName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastRestockedDate).HasColumnType("datetime");
            entity.Property(e => e.ManufacturerPartNumber)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.QuickBooksInvId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("QuickBooksInvID");
            entity.Property(e => e.SalesPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.IncomeAccount).WithMany(p => p.InventoryData)
                .HasForeignKey(d => d.IncomeAccountId)
                .HasConstraintName("FK__Inventory__Incom__5FB337D6");
        });

        modelBuilder.Entity<InventoryDocument>(entity =>
        {
            entity.HasKey(e => e.InventoryDocumentId).HasName("PK__Inventor__1A4F64173D88C100");

            entity.ToTable("InventoryDocument");

            entity.Property(e => e.InventoryDocumentId).HasColumnName("InventoryDocumentID");
            entity.Property(e => e.DocumentTypeId).HasColumnName("DocumentTypeID");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("FileURL");
            entity.Property(e => e.InventoryId).HasColumnName("InventoryID");
            entity.Property(e => e.UploadDate).HasColumnType("datetime");
            entity.Property(e => e.UploadedBy)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.DocumentType).WithMany(p => p.InventoryDocuments)
                .HasForeignKey(d => d.DocumentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryDocuments_DocumentTypes");

            entity.HasOne(d => d.Inventory).WithMany(p => p.InventoryDocuments)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryDocuments_InventoryData");
        });

        modelBuilder.Entity<Labour>(entity =>
        {
            entity.HasKey(e => e.LabourId).HasName("PK__Labour__74A96217720C8D93");

            entity.ToTable("Labour");

            entity.Property(e => e.LabourId).HasColumnName("LabourID");
            entity.Property(e => e.DateOfLabour).HasColumnType("date");
            entity.Property(e => e.FinishLabour).HasColumnType("datetime");
            entity.Property(e => e.FlatRateJobDescription)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.OttotalHrs).HasColumnName("OTTotalHrs");
            entity.Property(e => e.OttotalMin).HasColumnName("OTTotalMin");
            entity.Property(e => e.StartLabour).HasColumnType("datetime");
            entity.Property(e => e.TechnicianWorkOrderId).HasColumnName("TechnicianWorkOrderID");
            entity.Property(e => e.WorkDescription)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.TechnicianWorkOrder).WithMany(p => p.Labours)
                .HasForeignKey(d => d.TechnicianWorkOrderId)
                .HasConstraintName("FK_Labour_TechnicianWorkOrder");
        });

        modelBuilder.Entity<MileageAndTime>(entity =>
        {
            entity.HasKey(e => e.MilageTimeId).HasName("PK__MileageA__A0D5FCDE569629AC");

            entity.ToTable("MileageAndTime");

            entity.Property(e => e.MilageTimeId).HasColumnName("MilageTimeID");
            entity.Property(e => e.DateOfMileageTime).HasColumnType("date");
            entity.Property(e => e.FinishTravel).HasColumnType("datetime");
            entity.Property(e => e.SheetId).HasColumnName("SheetID");
            entity.Property(e => e.StartTravel).HasColumnType("datetime");

            entity.HasOne(d => d.Sheet).WithMany(p => p.MileageAndTimes)
                .HasForeignKey(d => d.SheetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MileageAn__Sheet__40058253");
        });

        modelBuilder.Entity<PartsUsed>(entity =>
        {
            entity.HasKey(e => e.PartUsedId).HasName("PK__PartsUse__F63FBD3DD8122046");

            entity.ToTable("PartsUsed");

            entity.Property(e => e.InventoryId).HasColumnName("InventoryID");
            entity.Property(e => e.Notes).IsUnicode(false);
            entity.Property(e => e.SheetId).HasColumnName("SheetID");

            entity.HasOne(d => d.Inventory).WithMany(p => p.PartsUseds)
                .HasForeignKey(d => d.InventoryId)
                .HasConstraintName("FK_PartsUsed_InventoryData");

            entity.HasOne(d => d.Sheet).WithMany(p => p.PartsUseds)
                .HasForeignKey(d => d.SheetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PartsUsed_WorkOrderSheet");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.PersonId).HasName("PK__Person__AA2FFB85FE5F2D9D");

            entity.ToTable("Person");

            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PhoneOne)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.RoleName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<ServiceDescription>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("PK__ServiceD__C51BB0EAFE16C469");

            entity.ToTable("ServiceDescription");

            entity.Property(e => e.ServiceId).HasColumnName("ServiceID");
            entity.Property(e => e.BillingId).HasColumnName("BillingID");
            entity.Property(e => e.Cost).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ServiceDescription1)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ServiceDescription");

            entity.HasOne(d => d.Billing).WithMany(p => p.ServiceDescriptions)
                .HasForeignKey(d => d.BillingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ServiceDe__Billi__208CD6FA");
        });

        modelBuilder.Entity<Technician>(entity =>
        {
            entity.HasKey(e => e.TechnicianId).HasName("PK__Technici__301F82C1FBE61792");

            entity.ToTable("Technician");

            entity.Property(e => e.TechnicianId).HasColumnName("TechnicianID");
            entity.Property(e => e.HourlyRate).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Notes).IsUnicode(false);
            entity.Property(e => e.PersonId).HasColumnName("PersonID");
            entity.Property(e => e.ShiftAvailibility)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.WorkStatus)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Person).WithMany(p => p.Technicians)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Technicia__Perso__3587F3E0");
        });

        modelBuilder.Entity<TechnicianExperience>(entity =>
        {
            entity.HasKey(e => e.ExperienceId).HasName("PK__Technici__2F4E3469AB34B49A");

            entity.ToTable("TechnicianExperience");

            entity.Property(e => e.ExperienceId).HasColumnName("ExperienceID");
            entity.Property(e => e.CertificatePdf).HasColumnName("CertificatePDF");
            entity.Property(e => e.CertificateUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("CertificateURL");
            entity.Property(e => e.SkillName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TechnicianId).HasColumnName("TechnicianID");

            entity.HasOne(d => d.Technician).WithMany(p => p.TechnicianExperiences)
                .HasForeignKey(d => d.TechnicianId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Technicia__Techn__4F47C5E3");
        });

        modelBuilder.Entity<TechnicianLicence>(entity =>
        {
            entity.HasKey(e => e.LicenseId).HasName("PK__Technici__72D600A2531F22DA");

            entity.Property(e => e.LicenseId).HasColumnName("LicenseID");
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.IssuedDate).HasColumnType("datetime");
            entity.Property(e => e.LicenceUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("LicenceURL");
            entity.Property(e => e.LicenseName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TechnicianId).HasColumnName("TechnicianID");

            entity.HasOne(d => d.Technician).WithMany(p => p.TechnicianLicences)
                .HasForeignKey(d => d.TechnicianId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Technicia__Techn__5224328E");
        });

        modelBuilder.Entity<TechnicianWorkOrder>(entity =>
        {
            entity.HasKey(e => e.TechnicianWorkOrderId).HasName("PK__Technici__7529718EADC1A1AC");

            entity.ToTable("TechnicianWorkOrder");

            entity.Property(e => e.TechnicianWorkOrderId).HasColumnName("TechnicianWorkOrderID");
            entity.Property(e => e.SheetId).HasColumnName("SheetID");
            entity.Property(e => e.TechnicianId).HasColumnName("TechnicianID");

            entity.HasOne(d => d.Sheet).WithMany(p => p.TechnicianWorkOrders)
                .HasForeignKey(d => d.SheetId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_TechnicianWorkOrder_SheetID");

            entity.HasOne(d => d.Technician).WithMany(p => p.TechnicianWorkOrders)
                .HasForeignKey(d => d.TechnicianId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TechnicianWorkOrder_Technician");
        });

        modelBuilder.Entity<VehicleDatum>(entity =>
        {
            entity.HasKey(e => e.VehicleId).HasName("PK__VehicleD__476B54B26AF0B11C");

            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");
            entity.Property(e => e.SamsaraVehicleId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SamsaraVehicleID");
            entity.Property(e => e.VehicleName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.VehicleVin)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("VehicleVIN");
        });

        modelBuilder.Entity<VehicleHistory>(entity =>
        {
            entity.HasKey(e => e.VehicleHistoryId).HasName("PK__VehicleH__A3B543D5CA216E56");

            entity.ToTable("VehicleHistory");

            entity.Property(e => e.VehicleHistoryId).HasColumnName("VehicleHistoryID");
            entity.Property(e => e.TravelTotal).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.VehicleHistories)
                .HasForeignKey(d => d.VehicleId)
                .HasConstraintName("FK_VehicleHistory_VehicleID");
        });

        modelBuilder.Entity<VehicleTravelLog>(entity =>
        {
            entity.HasKey(e => e.VehicleTravelId).HasName("PK__VehicleT__30F5990CA15D4699");

            entity.ToTable("VehicleTravelLog");

            entity.Property(e => e.VehicleTravelId).HasColumnName("VehicleTravelID");
            entity.Property(e => e.DateTimeEnd).HasColumnType("datetime");
            entity.Property(e => e.DateTimeStart).HasColumnType("datetime");
            entity.Property(e => e.EndingLocation)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.KmatEnd)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("KMAtEnd");
            entity.Property(e => e.KmatStart)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("KMAtStart");
            entity.Property(e => e.StartingLocation)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TotalKms).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");
            entity.Property(e => e.VehicleWorkOrderId).HasColumnName("VehicleWorkOrderID");

            entity.HasOne(d => d.VehicleWorkOrder).WithMany(p => p.VehicleTravelLogs)
                .HasForeignKey(d => d.VehicleWorkOrderId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_VehicleTravelLog_VehicleWorkOrderID");
        });

        modelBuilder.Entity<VehicleWorkOrder>(entity =>
        {
            entity.HasKey(e => e.VehicleWorkOrderId).HasName("PK__VehicleW__B975A16A4016301D");

            entity.ToTable("VehicleWorkOrder");

            entity.Property(e => e.VehicleWorkOrderId).HasColumnName("VehicleWorkOrderID");
            entity.Property(e => e.SheetId).HasColumnName("SheetID");
            entity.Property(e => e.VehicleId).HasColumnName("VehicleID");

            entity.HasOne(d => d.Sheet).WithMany(p => p.VehicleWorkOrders)
                .HasForeignKey(d => d.SheetId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_VehicleWorkOrder_SheetID");

            entity.HasOne(d => d.Vehicle).WithMany(p => p.VehicleWorkOrders)
                .HasForeignKey(d => d.VehicleId)
                .HasConstraintName("FK_VehicleWorkOrder_VehicleID");
        });

        modelBuilder.Entity<WorkOrderCounter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WorkOrde__3214EC0781D9C1CC");

            entity.ToTable("WorkOrderCounter");

            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<WorkOrderSheet>(entity =>
        {
            entity.HasKey(e => e.SheetId).HasName("PK__WorkOrde__30B2738861CB949F");

            entity.ToTable("WorkOrderSheet");

            entity.Property(e => e.SheetId).HasColumnName("SheetID");
            entity.Property(e => e.DateTimeCompleted)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DateTimeCreated).HasColumnType("datetime");
            entity.Property(e => e.DateTimeStarted)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.WorkOrdStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}