// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class RegularLabour
{
    public int LabourId { get; set; }

    public int? TechnicianWorkOrderId { get; set; }

    public DateTime DateOfLabor { get; set; }

    public DateTime? StartLabor { get; set; }

    public DateTime? FinishLabor { get; set; }

    public string WorkDescription { get; set; }

    public DateTime? DateLabourStarted { get; set; }

    public DateTime? DateLabourFinished { get; set; }

    public int? TotalHours { get; set; }

    public int? TotalMinutes { get; set; }

    public int? TotalOthours { get; set; }

    public int? TotalOtminutes { get; set; }

    public int LabourTypeId { get; set; }
}