// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class RolePermission
{
    public int RoleId { get; set; }

    public bool CanDownloadFromCloud { get; set; }

    public bool CanUploadToCloud { get; set; }

    public bool CanApprove { get; set; }

    public bool CanAssignTech { get; set; }

    public bool CanExportInvoice { get; set; }

    public virtual Role Role { get; set; }
}