// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class TechnicianExperience
{
    public int ExperienceId { get; set; }

    public int TechnicianId { get; set; }

    public string SkillName { get; set; }

    public int? YearsOfExperience { get; set; }

    public byte[] CertificatePdf { get; set; }

    public string CertificateUrl { get; set; }

    public virtual Technician Technician { get; set; }
}