// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class TechnicianAndType
{
    public int TechTypeAssignId { get; set; }

    public int TechnicianId { get; set; }

    public int TechTypeId { get; set; }

    public int FlatLabourId { get; set; }

    public decimal? RateOverride { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public bool IsPrimary { get; set; }

    public virtual FlatLabour FlatLabour { get; set; }

    public virtual TechnicianType TechType { get; set; }

    public virtual Technician Technician { get; set; }
}