// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class TechnicianLicence
{
    public int LicenseId { get; set; }

    public int TechnicianId { get; set; }

    public string LicenseName { get; set; }

    public DateTime? IssuedDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string LicenceUrl { get; set; }

    public virtual Technician Technician { get; set; }
}