// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class TechnicianWorkOrder
{
    public int TechnicianWorkOrderId { get; set; }

    public int? SheetId { get; set; }

    public int TechnicianId { get; set; }

    public virtual ICollection<Labour> Labours { get; set; } = new List<Labour>();

    public virtual WorkOrderSheet Sheet { get; set; }

    public virtual Technician Technician { get; set; }

    public virtual ICollection<WorkOrderFee> WorkOrderFees { get; set; } = new List<WorkOrderFee>();
}