// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class TechnicianType
{
    public int TechTypeId { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }
}