// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VehicleDatum
{
    public int VehicleId { get; set; }

    public string VehicleName { get; set; }

    public string SamsaraVehicleId { get; set; }

    public string VehicleVin { get; set; }

    public virtual ICollection<VehicleHistory> VehicleHistories { get; set; } = new List<VehicleHistory>();

    public virtual ICollection<VehicleTravelLog> VehicleTravelLogs { get; set; } = new List<VehicleTravelLog>();
}