// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VehicleTravelLog
{
    public int VehicleTravelId { get; set; }

    public int VehicleId { get; set; }

    public DateTime DateTimeStart { get; set; }

    public DateTime DateTimeCurrent { get; set; }

    public decimal? KmatStart { get; set; }

    public decimal? Kmcurrent { get; set; }

    public string StartingLocation { get; set; }

    public string CurrentLocation { get; set; }

    public int? WorkOrderId { get; set; }

    public int? VehicleWorkOrderId { get; set; }

    public virtual VehicleWorkOrder VehicleWorkOrder { get; set; }
}