// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VehicleTravelLog
{
    public int VehicleTravelId { get; set; }

    public int VehicleId { get; set; }

    public DateTime DateTimeStart { get; set; }

    public decimal? KmatStart { get; set; }

    public string StartingLocation { get; set; }

    public int? VehicleWorkOrderId { get; set; }

    public DateTime DateTimeEnd { get; set; }

    public string EndingLocation { get; set; }

    public decimal? KmatEnd { get; set; }

    public virtual VehicleWorkOrder VehicleWorkOrder { get; set; }
}