// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VehicleWorkOrder
{
    public int VehicleWorkOrderId { get; set; }

    public int VehicleId { get; set; }

    public int? SheetId { get; set; }

    public virtual WorkOrderSheet Sheet { get; set; }

    public virtual VehicleDatum Vehicle { get; set; }

    public virtual ICollection<VehicleTravelLog> VehicleTravelLogs { get; set; } = new List<VehicleTravelLog>();
}