// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwFlatLabourQbmatch
{
    public string MatchedQb { get; set; }

    public int FlatLabourId { get; set; }

    public string LabourName { get; set; }

    public string LabourDescription { get; set; }

    public string ListId { get; set; }
}