// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwInventoryDifference
{
    public string ListId { get; set; }

    public string DataMpn { get; set; }

    public string StagingMpn { get; set; }

    public string DataMpnDesc { get; set; }

    public string StagingMpnPurchaseDesc { get; set; }

    public decimal? DataCost { get; set; }

    public decimal? StagingPurchaseCost { get; set; }

    public decimal? DataSalesPrice { get; set; }

    public decimal? StagingSalesPrice { get; set; }

    public int? DataOnHand { get; set; }

    public int? StagingOnHand { get; set; }

    public int DiffMpn { get; set; }

    public int DiffDesc { get; set; }

    public int DiffCost { get; set; }

    public int DiffSalesPrice { get; set; }

    public int DiffOnHand { get; set; }

    public int IsDifferent { get; set; }

    public DateTime? TimeModified { get; set; }

    public DateTime CreatedAtUtc { get; set; }
}