// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwInvoiceLineExport
{
    public int InvoiceId { get; set; }

    public int WorkOrderId { get; set; }

    public string ItemListId { get; set; }

    public string SourceType { get; set; }

    public string TechnicianName { get; set; }

    public string ItemNameSnapshot { get; set; }

    public string Description { get; set; }

    public decimal? Qty { get; set; }

    public decimal? Rate { get; set; }

    public decimal? Amount { get; set; }
}