// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwInventoryNew
{
    public string ListId { get; set; }

    public string Name { get; set; }

    public string ManufacturerPartNum { get; set; }

    public string PurchaseDesc { get; set; }

    public string SalesDesc { get; set; }

    public decimal? PurchaseCost { get; set; }

    public decimal? SalesPrice { get; set; }

    public int? OnHand { get; set; }

    public DateTime? TimeModified { get; set; }

    public DateTime CreatedAtUtc { get; set; }
}