// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwInventoryUpsertWork
{
    public string QuickBooksInvId { get; set; }

    public string ItemName { get; set; }

    public string Description { get; set; }

    public decimal? Cost { get; set; }

    public decimal? SalesPrice { get; set; }

    public int? OnHand { get; set; }

    public string ManufacturerPartNumber { get; set; }

    public DateTime? SourceTimeModified { get; set; }

    public byte[] StagingRowHash { get; set; }

    public byte[] CoreRowHash { get; set; }

    public string ActionCode { get; set; }

    public int UpsertPriority { get; set; }
}