// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwInvoicePreviewExport
{
    public string Category { get; set; }

    public int? SheetId { get; set; }

    public int? TechnicianId { get; set; }

    public string TechnicianName { get; set; }

    public string ItemName { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? TotalQty { get; set; }

    public decimal? TotalAmount { get; set; }

    public string QuickBooksInvId { get; set; }

    public int? SourceInventoryId { get; set; }

    public int? CustomerId { get; set; }

    public string CustomerListId { get; set; }
}