// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwPersonWithTechProfile
{
    public int PersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string RoleName { get; set; }

    public string PhoneOne { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int? RoleId { get; set; }

    public int? TechnicianId { get; set; }

    public string WorkStatus { get; set; }

    public decimal? HourlyRate { get; set; }

    public string Notes { get; set; }

    public int? TechTypeAssignId { get; set; }

    public int? TechTypeId { get; set; }

    public string TypeName { get; set; }

    public int? FlatLabourId { get; set; }

    public string LabourName { get; set; }

    public decimal? EffectiveRate { get; set; }
}