// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwRole
{
    public int TechnicianId { get; set; }

    public int PersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public bool CanDownloadFromCloud { get; set; }

    public bool CanUploadToCloud { get; set; }

    public bool CanApprove { get; set; }

    public bool CanAssignTech { get; set; }
}