// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwTechnicianTypeRate
{
    public int TechTypeAssignId { get; set; }

    public int TechnicianId { get; set; }

    public int TechTypeId { get; set; }

    public string TypeName { get; set; }

    public int FlatLabourId { get; set; }

    public string LabourName { get; set; }

    public string LabourDescription { get; set; }

    public decimal BaseRate { get; set; }

    public decimal? RateOverride { get; set; }

    public decimal? EffectiveRate { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime? EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }
}