// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class VwWorkOrderTechnician
{
    public int? SheetId { get; set; }

    public int? TechnicianId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}