// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class WorkOrderSyncEvent
{
    public int LogId { get; set; }

    public int SheetId { get; set; }

    public string DeviceId { get; set; }

    public string EventType { get; set; }

    public DateTime Timestamp { get; set; }

    public int? UserId { get; set; }
}