// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class WorkOrderStatusSetup
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public string IconName { get; set; }

    public string HexColor { get; set; }
}