// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class WorkOrderFee
{
    public int WorkOrderFeeId { get; set; }

    public int TechnicianWorkOrderId { get; set; }

    public int FlatLabourId { get; set; }

    public int LabourTypeId { get; set; }

    public int Qty { get; set; }

    public string WorkDescription { get; set; }

    public int? ItemId { get; set; }

    public virtual FlatLabour FlatLabour { get; set; }

    public virtual ChargeItem Item { get; set; }

    public virtual LabourType LabourType { get; set; }

    public virtual TechnicianWorkOrder TechnicianWorkOrder { get; set; }
}