// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class WorkOrderSyncLog
{
    public int LogId { get; set; }

    public int SheetId { get; set; }

    public string DeviceId { get; set; }

    public DateTime SyncedOn { get; set; }

    public virtual WorkOrderSheet Sheet { get; set; }
}