// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class WorkOrderLine
{
    public int LineId { get; set; }

    public int SheetId { get; set; }

    public int ItemId { get; set; }

    public decimal Qty { get; set; }

    public decimal? UnitRate { get; set; }

    public string DescriptionOverride { get; set; }

    public decimal? Amount { get; set; }

    public virtual ChargeItem Item { get; set; }

    public virtual WorkOrderSheet Sheet { get; set; }
}