// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaymarEquipmentInventory.Models;

public partial class WorkOrderStatus
{
    public int StatusId { get; set; }

    public DateTime DateTimeCreated { get; set; }

    public string StatusName { get; set; }

    public int? WorkOrdTypeId { get; set; }

    public string IconName { get; set; }

    public string HexColor { get; set; }

    public virtual WorkOrderType WorkOrdType { get; set; }

    public virtual ICollection<WorkOrderSheet> WorkOrderSheets { get; set; } = new List<WorkOrderSheet>();

    public virtual ICollection<WorkOrderType> WorkOrdTypes { get; set; } = new List<WorkOrderType>();
}